### ISSUE TITLE
Build for linux/arm

### ISSUE THREAD

**Issue by ItsDrike** [tmknight/docker-nordvpn#40]
Hey, I found your fork, however I noticed unlike [the original bubuntux/nordvpn](https://github.com/bubuntux/nordvpn/pkgs/container/nordvpn),  you're not building images for ARM 64 architecture, would you mind adding it?

**Comment by tmknight** [comment]
I have no way to test, so you'll have to be my arms (PI): https://github.com/tmknight/docker-nordvpn/pkgs/container/nordvpn/76510167?tag=develop

**Comment by ItsDrike** [comment]
Everything seems to be working great, except for the healthcheck. When I have a
```yaml
    depends_on:
      vpn:
        condition: service_healthy
```

As a part of some service in my docker-compose, I'm seeing `ERROR: for [container name]  Container "[container id]" is unhealthy.`

The `[container name]` here isn't `vpn` (the name of the container with this image), but rather the service that depends on it. I can't replicate this with the same docker-compose when running it on x86, so it seems like it is related to this. Any thoughts?

**Comment by tmknight** [comment]
You'll have to share your compose file as what you have provided is not enough info to be able to provide you assistance.

**Comment by ItsDrike** [comment]
Sure, though I can't give you the python source code running in the `proj` service, but my use-case is indeed a bit uncommon. What I'm doing is passing over the nordvpn socket, and controlling nordvpn from another container, using the CLI, since I needed to be able to switch servers, not just stay behind a single one. I do this first time the script starts, once a connection to the selenium chromedriver is established, then I connect to a random VPN server from the `proj` service, and use selenium to visit some webpage.

One issue is that as I said, if the `proj` depends on `vpn` via healthcheck, it never starts. So I moved to depend on `service_started` instead (the docker-compose below still has `service_healthy`). When doing this, I see the logs I sent above, and then from the `proj` service, I try to make an HTTP request (still outside selenium - using python's urllib), which already fails, after which the `WARNING: Unstable connection detected` is shown. This is still before I even attempt to change the VPN server with the CLI, so this should be using the connection established at the start from the `vpn` service. Here's the logs:

<details>
<summary>Logs directly from docker compose</summary>

```
chrome_1   | 2023-03-16 10:44:40,483 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
chrome_1   | 2023-03-16 10:44:40,508 INFO RPC interface 'supervisor' initialized
chrome_1   | 2023-03-16 10:44:40,509 CRIT Server 'unix_http_server' running without any HTTP authentication checking
chrome_1   | 2023-03-16 10:44:40,509 INFO supervisord started with pid 8
chrome_1   | 2023-03-16 10:44:41,511 INFO spawned: 'xvfb' with pid 9
chrome_1   | 2023-03-16 10:44:41,513 INFO spawned: 'vnc' with pid 10
chrome_1   | 2023-03-16 10:44:41,515 INFO spawned: 'novnc' with pid 11
chrome_1   | 2023-03-16 10:44:41,516 INFO spawned: 'selenium-standalone' with pid 13
chrome_1   | Setting up SE_NODE_GRID_URL...
chrome_1   | 2023-03-16 10:44:41,527 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1   | 2023-03-16 10:44:41,527 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1   | 2023-03-16 10:44:41,527 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1   | 2023-03-16 10:44:41,527 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1   | Selenium Grid Standalone configuration:
chrome_1   | [network]
chrome_1   | relax-checks = true
chrome_1   |
chrome_1   | [node]
chrome_1   | session-timeout = "300"
chrome_1   | override-max-sessions = false
chrome_1   | detect-drivers = false
chrome_1   | drain-after-session-count = 0
chrome_1   | max-sessions = 1
chrome_1   |
chrome_1   | [[node.driver-configuration]]
chrome_1   | display-name = "chrome"
chrome_1   | stereotype = '{"browserName": "chrome", "browserVersion": "111.0", "platformName": "Linux"}'
chrome_1   | max-sessions = 1
chrome_1   |
chrome_1   | Starting Selenium Grid Standalone...
chrome_1   | Tracing is disabled
chrome_1   | 10:44:42.414 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
chrome_1   | 10:44:42.421 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
chrome_1   | 10:44:43.680 INFO [NodeOptions.getSessionFactories] - Detected 2 available processors
chrome_1   | 10:44:43.737 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "111.0","se:noVncPort": 7900,"browserName": "chrome","platformName": "LINUX","se:vncEnabled": true} 1 times
chrome_1   | 10:44:43.754 INFO [Node.<init>] - Binding additional locator mechanisms: relative
chrome_1   | 10:44:43.780 INFO [GridModel.setAvailability] - Switching Node 4aa7a795-33bd-42e9-b801-848ee51cfece (uri: http://10.5.0.3:4444) from DOWN to UP
chrome_1   | 10:44:43.781 INFO [LocalDistributor.add] - Added node 4aa7a795-33bd-42e9-b801-848ee51cfece at http://10.5.0.3:4444. Health check every 120s
chrome_1   | 10:44:43.960 INFO [Standalone.execute] - Started Selenium Standalone 4.8.1 (revision 8ebccac989): http://10.5.0.3:4444
vpn_1      | 2023-03-16 10:44:40+0000	INFO	Firewall is up; traffic will be routed through vpn
vpn_1      | 2023-03-16 10:44:40+0000	INFO	Enabling connection to secure interface and docker network
vpn_1      | 2023-03-16 10:44:40+0000	INFO	Waiting for nord daemon to start...
vpn_1      | 2023-03-16 10:44:42+0000	INFO	Configuring and connecting NordVPN...
vpn_1      | ########################
vpn_1      | NordVPN Version 3.15.5
Technology is already set to 'NORDLYNX'.
Firewall is already set to 'enabled'.
Kill Switch is already set to 'disabled'.
Subnet 10.5.0.0/16 is whitelisted successfully.
vpn_1      | Login successful; connection now in progress...
vpn_1      | The recommended server is de1023
Connecting to Germany #1023 (de1023.nordvpn.com)
You are connected to Germany #1023 (de1023.nordvpn.com)!
vpn_1      | ########################
vpn_1      | 2023-03-16 10:44:46+0000	INFO	Startup complete
vpn_1      | 2023-03-16 10:44:46+0000	INFO	Periodic VPN connection refresh is disabled
proj_1  | 2023-03-16 10:45:11 | urllib3.connectionpool | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9ad61a50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
proj_1  | 2023-03-16 10:45:31 | urllib3.connectionpool | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9ad62380>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
proj_1  | 2023-03-16 10:45:51 | urllib3.connectionpool | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9ad60910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
vpn_1      | 2023-03-16 10:46:06+0000	WARNING	Unstable connection detected
vpn_1      | ########################
Status: Connected
vpn_1      | Hostname: de1023.nordvpn.com
vpn_1      | IP: 5.180.62.179
vpn_1      | Country: Germany
vpn_1      | City: Frankfurt
vpn_1      | Current technology: NORDLYNX
vpn_1      | Current protocol: UDP
vpn_1      | Transfer: 92 B received, 12.08 KiB sent
vpn_1      | Uptime: 1 minute 20 seconds
proj_1  | Traceback (most recent call last):
proj_1  |   File "/opt/poetry/cache/virtualenvs/proj-j2DLyHZE-py3.10/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
proj_1  |     conn = connection.create_connection(
proj_1  |   File "/opt/poetry/cache/virtualenvs/proj-j2DLyHZE-py3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
proj_1  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
proj_1  |   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
proj_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
proj_1  | socket.gaierror: [Errno -3] Temporary failure in name resolution
```
</details>

This runs perfectly fine on my Arch Linux x86 machine with docker 23.0.1, and docker-compose 2.16.0.

However on my Amazon Linux 2 AMI server, on ARM architecture, with docker 20.10.17 and docker-compose 1.29.2, the issue I posted above appears.

<details>
<summary>docker-compose.yml</summary>

```yml
version: "3.7"

services:
  vpn:
    image: tmknight88/nordvpn:3.15.5-2.3.3-rc1
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      TOKEN: "${NORD_VPN_TOKEN}"
      KILLSWITCH: "false"
      REFRESH_CONNECTION_INTERVAL: "0"
    volumes:
      - type: bind
        source: ./.nordvpn/
        target: /run/nordvpn/
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      vpn_network:
        ipv4_address: 10.5.0.3

  chrome:
    image: seleniarm/standalone-chromium
    restart: unless-stopped
    shm_size: 3gb
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 10s
      timeout: 3s
      retries: 2
      start_period: 15s
    # Use same network space as vpn service (on same IP, same docker network - vpn_network)
    network_mode: service:vpn
    depends_on:
      vpn:
        condition: service_healthy

  proj:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - type: bind
        source: .
        target: /proj
        read_only: true
      - type: bind
        source: ./output.log
        target: /proj/output.log
      - type: bind
        source: ./.nordvpn/
        target: /run/nordvpn/
    # Use same network space as vpn service (on same IP, same docker network - vpn_network)
    network_mode: service:vpn
    depends_on:
      chrome:
        condition: service_healthy
      vpn:
        condition: service_healthy
    env_file:
      - .env
    environment:
      CHROME_WEBDRIVER_REMOTE_URL: 10.5.0.3:4444

networks:
  vpn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

```
</details>

<details>
<summary>Dockerfile</summary>

```dockerfile
FROM python:3.10-slim

ENV POETRY_VERSION=1.3.1 \
  POETRY_HOME="/opt/poetry/home" \
  POETRY_CACHE_DIR="/opt/poetry/cache" \
  POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_IN_PROJECT=false

ENV PATH="$POETRY_HOME/bin:$PATH"

RUN apt-get update \
  && apt-get -y upgrade \
  && apt-get install --no-install-recommends -y curl \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install NordVPN cli client
RUN curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh | bash -s -- -n

# Install poetry using the official installer
RUN curl -sSL https://install.python-poetry.org | python

# Limit amount of concurrent install requests, to avoid hitting pypi rate-limits
RUN poetry config installer.max-workers 10

# Install project dependencies
WORKDIR /proj
COPY pyproject.toml poetry.lock ./
RUN poetry install --only main --no-interaction --no-ansi -vvv

# Copy the source code in last to optimize rebuilding the image
COPY . .

ENTRYPOINT ["poetry"]
CMD ["run", "python", "-m", "proj"]
```
</details>
